language: r
sudo: false
cache: packages

addons:
    apt:
        packages:
            - graphviz

r_github_packages:
    - jimhester/covr
    - basilrabi /mansched

after_success:
    - Rscript -e 'covr::codecov()'
