dist: bionic
language: r
cache: packages
warnings_are_errors: false

addons:
    apt:
        packages:
            - graphviz

r_github_packages:
    - r-lib/covr

after_success:
    - Rscript -e 'covr::codecov()'
