language: r
sudo: false
cache: packages

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-7
            - graphviz

after_success:
    - Rscript -e 'covr::codecov()'

compiler:
    - g++
