language: r
sudo: required
dist: trusty
cache: packages

addons:
    apt:
        packages:
            - graphviz

before_install:
  - curl -OLs https://eddelbuettel.github.io/r-travis/run.sh && chmod 0755 run.sh
  - ./run.sh bootstrap

install:
  - ./run.sh install_aptget  r-cran-rcpp r-cran-runit


after_success:
    - Rscript -e 'covr::codecov()'
