language: r
sudo: false
cache: packages

addons:
    apt:
        packages:
            - graphviz

r_github_packages:
    - basilrabi/readODS
    - jimhester/covr

after_success:
    - Rscript -e 'covr::codecov()'
