library(mansched)

test_that("idAssetGroup() works", {
  expect_equal(idAssetGroup(NA)           , as.character(NA))
  expect_equal(idAssetGroup("ADMIN")      , "ADMIN")
  expect_equal(idAssetGroup("BRGY")       , "LGU")
  expect_equal(idAssetGroup("CIP XX")     , "CIP")
  expect_equal(idAssetGroup("Crusher")    , "MOC")
  expect_equal(idAssetGroup("CT 15")      , "CT")
  expect_equal(idAssetGroup("DT 101")     , "DT")
  expect_equal(idAssetGroup("EQ 101")     , "EQ")
  expect_equal(idAssetGroup("FAST CRAFT") , "FASTCRAFT")
  expect_equal(idAssetGroup("FL 5")       , "FL")
  expect_equal(idAssetGroup("FLY SQUID")  , "FS")
  expect_equal(idAssetGroup("forklift 2") , "FORKLIFT")
  expect_equal(idAssetGroup("FT 5")       , "FT")
  expect_equal(idAssetGroup("FTR 5")      , "FTR")
  expect_equal(idAssetGroup("GS 5 XX")    , "GS")
  expect_equal(idAssetGroup("GEN SET")    , "GS")
  expect_equal(idAssetGroup("GENERATOR")  , "GS")
  expect_equal(idAssetGroup("HPK DT 1")   , "HPK")
  expect_equal(idAssetGroup("Marketing")  , "MKTG")
  expect_equal(idAssetGroup("MC")         , "MC")
  expect_equal(idAssetGroup("MDT 1")      , "MDT")
  expect_equal(idAssetGroup("ML 5")       , "ML")
  expect_equal(idAssetGroup("MT 5")       , "MT")
  expect_equal(idAssetGroup("MWL 5")      , "MWL")
  expect_equal(idAssetGroup("NBC DT 5")   , "NBC")
  expect_equal(idAssetGroup("PACE XX")    , "PACE")
  expect_equal(idAssetGroup("Patrolboat") , "PATROLBOAT")
  expect_equal(idAssetGroup("Pumpboat")   , "PB")
  expect_equal(idAssetGroup("RG 15")      , "RG")
  expect_equal(idAssetGroup("SB 15")      , "SB")
  expect_equal(idAssetGroup("SDMC DT 15") , "SDMC")
  expect_equal(idAssetGroup("Security")   , "SECURITY")
  expect_equal(idAssetGroup("SMCC")       , "SMCC")
  expect_equal(idAssetGroup("SP 96")      , "SP")
  expect_equal(idAssetGroup("ST 96")      , "ST")
  expect_equal(idAssetGroup("TACOPHIL")   , "TACOPHIL")
  expect_equal(idAssetGroup("TL 96")      , "TL")
  expect_equal(idAssetGroup("TRGC TL 96") , "TRGC")
  expect_equal(idAssetGroup("TX 96")      , "TX")
  expect_equal(idAssetGroup("VC 96")      , "VC")
  expect_equal(idAssetGroup("WL 96")      , "WL")
  expect_equal(idAssetGroup("WP 96")      , "WP")
  expect_equal(idAssetGroup("WTL 96")     , "WTL")
  expect_equal(idAssetGroup("WX 96")      , "WX")
  expect_equal(idAssetGroup("YBM 96")     , "YBM")
  expect_equal(idAssetGroup("XXX")        , "ZZZ")
})

rm(list = ls())
