library(mansched)

test_that("identifyEquipment() works", {
  expect_equal(identifyEquipment(NA)           , NA)
  expect_equal(identifyEquipment("ADMIN")      , "ADMIN")
  expect_equal(identifyEquipment("BRGY")       , "LGU")
  expect_equal(identifyEquipment("CIP XX")     , "CIP")
  expect_equal(identifyEquipment("Crusher")    , "MOC")
  expect_equal(identifyEquipment("CT 15")      , "CT")
  expect_equal(identifyEquipment("DT 101")     , "DT")
  expect_equal(identifyEquipment("EQ 101")     , "EQ")
  expect_equal(identifyEquipment("FAST CRAFT") , "FASTCRAFT")
  expect_equal(identifyEquipment("FL 5")       , "FL")
  expect_equal(identifyEquipment("FLY SQUID")  , "FS")
  expect_equal(identifyEquipment("forklift 2") , "FORKLIFT")
  expect_equal(identifyEquipment("FT 5")       , "FT")
  expect_equal(identifyEquipment("FTR 5")      , "FTR")
  expect_equal(identifyEquipment("GS 5")       , "GS")
  expect_equal(identifyEquipment("HPK DT 1")   , "HPK")
  expect_equal(identifyEquipment("Marketing")  , "MKTG")
  expect_equal(identifyEquipment("MC")         , "MC")
  expect_equal(identifyEquipment("MDT 1")      , "MDT")
  expect_equal(identifyEquipment("ML 5")       , "ML")
  expect_equal(identifyEquipment("MT 5")       , "MT")
  expect_equal(identifyEquipment("MWL 5")      , "MWL")
  expect_equal(identifyEquipment("NBC DT 5")   , "NBC")
  expect_equal(identifyEquipment("PACE XX")    , "PACE")
  expect_equal(identifyEquipment("Patrolboat") , "PATROLBOAT")
  expect_equal(identifyEquipment("Pumpboat")   , "PB")
  expect_equal(identifyEquipment("RG 15")      , "RG")
  expect_equal(identifyEquipment("SB 15")      , "SB")
  expect_equal(identifyEquipment("SDMC DT 15") , "SDMC")
  expect_equal(identifyEquipment("Security")   , "SECURITY")
  expect_equal(identifyEquipment("SMCC")       , "SMCC")
  expect_equal(identifyEquipment("SP 96")      , "SP")
  expect_equal(identifyEquipment("ST 96")      , "ST")
  expect_equal(identifyEquipment("TACOPHIL")   , "TACOPHIL")
  expect_equal(identifyEquipment("TL 96")      , "TL")
  expect_equal(identifyEquipment("TRGC TL 96") , "TRGC")
  expect_equal(identifyEquipment("TX 96")      , "TX")
  expect_equal(identifyEquipment("VC 96")      , "VC")
  expect_equal(identifyEquipment("WL 96")      , "WL")
  expect_equal(identifyEquipment("WP 96")      , "WP")
  expect_equal(identifyEquipment("WTL 96")     , "WTL")
  expect_equal(identifyEquipment("WX 96")      , "WX")
  expect_equal(identifyEquipment("YBM 96")     , "YBM")
  expect_equal(identifyEquipment("XXX")        , "ZZZ")
})
