// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// idAssetGroup
StringVector idAssetGroup(StringVector x);
RcppExport SEXP _mansched_idAssetGroup(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< StringVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(idAssetGroup(x));
    return rcpp_result_gen;
END_RCPP
}
// assignPool2
List assignPool2(DataFrame empReq, DataFrame empPool, List listT, List listR, CharacterVector prioStat, bool prioCode);
RcppExport SEXP _mansched_assignPool2(SEXP empReqSEXP, SEXP empPoolSEXP, SEXP listTSEXP, SEXP listRSEXP, SEXP prioStatSEXP, SEXP prioCodeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type empReq(empReqSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type empPool(empPoolSEXP);
    Rcpp::traits::input_parameter< List >::type listT(listTSEXP);
    Rcpp::traits::input_parameter< List >::type listR(listRSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type prioStat(prioStatSEXP);
    Rcpp::traits::input_parameter< bool >::type prioCode(prioCodeSEXP);
    rcpp_result_gen = Rcpp::wrap(assignPool2(empReq, empPool, listT, listR, prioStat, prioCode));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mansched_idAssetGroup", (DL_FUNC) &_mansched_idAssetGroup, 1},
    {"_mansched_assignPool2", (DL_FUNC) &_mansched_assignPool2, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_mansched(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
