# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Identify asset group
#'
#' Identifies the asset group of a given equipment (or entity) which is the
#'   recipient of the item withdrawn from warehouse.
#'   This data can be seen from warehouse issuance slips.
#'
#'   Below are the identified groups:
#'   \itemize{
#'   \item Contractors
#'     \describe{
#'     \item{HPK}{}
#'     \item{NBC}{Nickel Base Corporation}
#'     \item{PACE}{PrinceAce Corporation}
#'     \item{SDMC}{Southernphil Development and Marketing Corporation
#'       (FITZ-SDMC)}
#'     \item{SMCC}{Sumitomo-Mitsui Construction Company}
#'     \item{TACOPHIL}{}
#'     \item{TRGC}{Tango Romeo General Construction}
#'     }
#'   \item Equipment
#'     \describe{
#'     \item{ATV}{all-terrain vehicle}
#'     \item{CM}{concrete mixer}
#'     \item{CT}{bulldozer}
#'     \item{DT}{dump truck}
#'     \item{FASTCRAFT}{}
#'     \item{FL}{fuel lorry}
#'     \item{FORKLIFT}{}
#'     \item{FS}{flying squid}
#'     \item{FT}{fire truck}
#'     \item{FTR}{farm tractors}
#'     \item{GS}{power generator set}
#'     \item{GT}{garbage truck}
#'     \item{LM}{lawn mower}
#'     \item{MC}{motorcycle}
#'     \item{MDT}{mini dump truck}
#'     \item{ML}{man lift}
#'     \item{MOC}{mobile crusher}
#'     \item{MT}{maintenance truck}
#'     \item{MTX}{mini tracked excavator}
#'     \item{MWL}{mini wheeled pay loader}
#'     \item{PATROLBOAT}{}
#'     \item{PB}{pump boat}
#'     \item{PMT}{prime mover truck}
#'     \item{RG}{road grader}
#'     \item{SB}{service bus}
#'     \item{SP}{service pickup}
#'     \item{ST}{service truck}
#'     \item{TL}{tracked pay loader}
#'     \item{TWL}{tower light}
#'     \item{TX}{tracked excavator}
#'     \item{VC}{vibrating compactor}
#'     \item{WC}{wheeled crane}
#'     \item{WL}{wheeled pay loader}
#'     \item{WP}{water pump}
#'     \item{WTL}{water lorry}
#'     \item{WX}{wheeled excavator}
#'     \item{YBM}{Yoshida Boring Machine}
#'     }
#'   \item Fixed assets
#'     \describe{
#'     \item{ADMIN}{Admin building}
#'     \item{EQ}{Engineer's Quarters}
#'     \item{CIP}{construction in-progress}
#'     }
#'   \item Other parties
#'     \describe{
#'     \item{LGU}{local government unit}
#'     \item{MKTG}{marketing}
#'     \item{SECURITY}{}
#'     }
#'   \item Unknown
#'     \itemize{
#'     \item WC
#'     \item ZZZ
#'     }
#'   }
#'
#' @param x a character vector representing the equipment
#' @return a character vector representing the asset group
#' @export
idAssetGroup <- function(x) {
    .Call('_mansched_idAssetGroup', PACKAGE = 'mansched', x)
}

#' Assign pool to requirement2 (WIP)
#'
#' This is used in \code{\link{assignPrio}}.
#'
#' @param empReq passed from \code{\link{assignPrio}}
#' @param empPool passed from \code{\link{assignPrio}}
#' @param listT list of theoretical employees created from empReq
#' @param listR list of real employees created fro empPool
#' @param prioStat character vector defining the employee status that are
#'   prioritized in assigning man hours
#' @param prioCode logical value \cr
#'   Is cost code prioritized in assigning?
#' @return a list containing the following:
#'   \enumerate{
#'     \item remaining empReq
#'     \item remaining empPool
#'     \item remaining listT
#'     \item remaining listR
#'     \item man hour database resulting from the assignment
#'
#'       This is also merged and described well in \code{\link{getmhDB}}.
#'   }
#' @export
assignPool2 <- function(empReq, empPool, listT, listR, prioStat = NA_character_, prioCode = FALSE) {
    .Call('_mansched_assignPool2', PACKAGE = 'mansched', empReq, empPool, listT, listR, prioStat, prioCode)
}

#' Interpolate
#'
#' This is used in a spatial study for limonite face samples.
#'
#' @param modelT data frame of prediction model
#' @param sample data frame of sample coordinates
#' @param radius numeric value representing buffer radius
#' @param vario List contaning variogram models
#' @return a dataframe containing the following:
#'   \enumerate{
#'     \item interpolated grade of element
#'     \item interpolation variance
#'     \item interpolation variance using absolute value of kriging weight
#'   }
#' @export
predictVars <- function(modelT, sample, radius, vario) {
    .Call('_mansched_predictVars', PACKAGE = 'mansched', modelT, sample, radius, vario)
}

