# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Identify asset group
#'
#' Identifies the asset group of a given equipment from accounting data.
#'
#' @param x a character vector representing the equipment
#' @return a character vector representing the asset group
#' @export
idAssetGroup <- function(x) {
    .Call('_mansched_idAssetGroup', PACKAGE = 'mansched', x)
}

