# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Assign pool to requirement faster
#'
#' This is used in \code{\link{assignPrio}}.
#'
#' @param empReq passed from \code{\link{assignPrio}}
#' @param empPool passed from \code{\link{assignPrio}}
#' @param listT list of theoretical employees created from empReq
#' @param listR list of real employees created fro empPool
#' @param prioStat character vector defining the employee status that are
#'   prioritized in assigning man hours
#' @param prioCode logical value \cr
#'   Is cost code prioritized in assigning?
#' @return a list containing the following:
#'   \enumerate{
#'     \item remaining empReq
#'     \item remaining empPool
#'     \item remaining listT
#'     \item remaining listR
#'     \item man hour database resulting from the assignment
#'
#'       This is also merged and described well in \code{\link{getmhDB}}.
#'   }
#' @export
assignPool <- function(empReq, empPool, listT, listR, prioStat = NA_character_, prioCode = FALSE) {
    .Call('_mansched_assignPool', PACKAGE = 'mansched', empReq, empPool, listT, listR, prioStat, prioCode)
}

#' Spend all available man hours
#'
#' Available man hours of a specific man hour type from an
#'   \code{\link{Employee-class}} object representing a real employee is
#'   assigned to the man hours of an \code{Employee-class} object representing
#'   an employee requirement.
#'
#' @param hoursT integer vector of length 12
#'
#'   This represents the man hours from a theoretical employee with a certain
#'   man hour type.
#' @param hoursR integer vector of length 12
#'
#'   This represents the man hours from a real employee with a certain man hour
#'   type.
#' @return an integer vector of length 12 representing the man-hours assigned
#'
#'   The hoursT and hoursR will also be reduced by the value of the returned
#'   integer vector.
#' @export
assignMH <- function(hoursT, hoursR) {
    .Call('_mansched_assignMH', PACKAGE = 'mansched', hoursT, hoursR)
}

#' Get remaining working hours
#'
#' This function returns all remaining man hour types including overtime.
#'
#' @param employee an \code{\link{Employee-class}} object
#' @return a \code{\link{data.frame}} representing the remaining man hours
#'
#'   Each row represents a month while each column represents a man hour type.
#' @export
getHours <- function(employee) {
    .Call('_mansched_getHours', PACKAGE = 'mansched', employee)
}

#' Paired Minimum
#'
#' Get minimum value between two integer vectors
#'
#' @param a integer vector
#' @param b integer vector
#' @return an integer vector with the least value for each element by element
#'   comparison between a and b
#' @export
getMin <- function(a, b) {
    .Call('_mansched_getMin', PACKAGE = 'mansched', a, b)
}

#' isReg
#'
#' Is the employee regular?
#'
#' @param theObject an \code{\link{Employee-class}} object
#' @return logical value
#' @export isReg
isReg <- function(theObject) {
    .Call('_mansched_isReg', PACKAGE = 'mansched', theObject)
}

